"""F0c single-frame denoise sweep: H3 as an image model through the tiled refine.

The owner spotted a semantic seam (split fingers) at frame 0 of the F0b stress runs,
worse on the text arm, absent in the base. This harness refines THAT frame alone —
a 1-frame video target, the same shape the fl2va keyframe path encodes single
images with — so denoise/conditioning settings sweep in minutes, not hours:

    for arm in (text, vl-slice):  for denoise in (0.32, 0.25, 0.22, 0.18):
        2x2 tiled refine of the upscaled frame -> H3F_<arm>_d<DD>.png

Geometry, anchors, overlap dissolve, canvas-sliced noise, and the slicing math are
imported from spike_h3_stress verbatim; the frame is re-derived from the cached
base latent (decode -> frame 0 -> 2x lanczos), never read back from a PNG. The VL
arm uses the IMAGE presentation ("<Picture 1>: " + one 4032-cell grid) — the
natural single-image form — sliced per tile exactly like the video blocks.

REGIME: the target is the model's MINIMUM VALID CLIP — the base's real first 5
frames (the 17k+5 grid floor, latent_t=2, audio_t=8) — judged and saved at frame
0. A true 1-frame target (latent_t=1) was tried first and produced frame-wide
artifacts on BOTH arms at every denoise (tone crush, blotchy water, smeared
birds): H3 does not tolerate a single latent frame, so 5 frames is the floor for
image-mode use of this model. Relative ordering across denoise/arms transfers to
video; absolute drift can still differ from the 124-frame runs (2 vs 37 latent
frames of context).

    <venv-python> tests-AB/spike_h3_frame.py
    <venv-python> tests-AB/spike_h3_frame.py --denoises 0.25 0.20 0.15
"""
import argparse
import faulthandler
import json

faulthandler.enable()

import ab_models  # noqa: E402
import spike_h3 as poc  # noqa: E402  (bootstraps the ComfyUI env: aimdo + memory flags)
import spike_h3_stress as stress  # noqa: E402
import torch  # noqa: E402

OUTPUT_DIR = poc.OUTPUT_DIR
CACHE_DIR = poc.CACHE_DIR
UP_W, UP_H = stress.UP_W, stress.UP_H

FRAME_INDEX = 0
FRAMES = 5                        # 17k+5 grid floor -> latent_t=2; 1 frame is OOD
LATENT_T = 2
AUDIO_T = 8                       # temporal_shape(5): round(5/24*40); frozen zeros
DEFAULT_DENOISES = (0.32, 0.25, 0.22, 0.18)
ARMS = ("text", "vl", "cap", "vlcap")

# AB27's caption register (run_ab_krea2.py CAPTION_INSTRUCTION), reused verbatim so
# the H3 caption arms test the same text object the Krea 2 factorial settled on.
CAPTION_INSTRUCTION = ("Describe the image by detailing the color, shape, size, "
                       "texture, quantity, text, spatial relationships of the "
                       "objects and background:")

# Captions are GENERATED by the Krea 2 4B (full model, caption-proven in AB27-40) and
# ENCODED by the minimax CLIP. H3's own encoder cannot caption: it is truncated to 50
# of 64 layers with no final norm, and clip.generate's tied-embedding fallback there
# degenerates to comma streams (found 2026-08-09 — non-empty, so it slipped past the
# Krea-era emptiness guards; _usable() now catches that class).
CAPTIONER_CLIP_NAME = "qwen3-vl-4b-heretic_int8.safetensors"
CAPTIONER_CLIP_TYPE = "krea2"

FRAME_KEY = dict(stress.STRESS_KEY, frame=FRAME_INDEX, clip_frames=FRAMES)


def upscaled_clip(vae):
    """The base's real first FRAMES frames, 2x lanczos'd — frame 0 bit-matches the
    H3S_upscaled_f000 artifact's source, without a PNG round trip."""
    import comfy.utils

    base_video, _ = stress.render_base_full(None, False)
    frames = poc.decode_video(vae, base_video)
    clip_frames = frames[:FRAMES].to(torch.float16)
    del frames
    with torch.inference_mode():
        up = comfy.utils.common_upscale(
            clip_frames.movedim(-1, 1), UP_W, UP_H, "lanczos", "disabled"
        ).movedim(1, -1).to(torch.float16).contiguous()
    return up


def encode_image_vl(frame_up, force):
    """ONE image-presentation encode of the upscaled frame, cached: "<Picture 1>: "
    + a single 4032-cell grid. Same layout-walk fail-fast as the video encode."""
    cache = ab_models.cache_path(CACHE_DIR, "h3frame", "vlimg", UP_W, UP_H, FRAME_KEY)
    if cache.is_file() and not force:
        payload = torch.load(cache, weights_only=True)
        print(f"VL image encode from cache: {cache.name}", flush=True)
        return payload["cond"], payload["tags"], payload["layout"]

    ab_models.free_gpu()
    print("VL image encode: loading 32B encoder...", flush=True)
    clip = ab_models.load_clip(poc.CLIP_NAME, poc.CLIP_TYPE)
    rows_per_block = (UP_H // 32) * (UP_W // 32)
    with ab_models.VramProbe() as probe, torch.inference_mode():
        tokens = clip.tokenize("", images=[frame_up])
        layout = []
        pos = 0
        for entry in tokens["qwen3vl_32b"][0]:
            if isinstance(entry[0], dict):
                layout.append(("grid", pos))
                pos += rows_per_block
            else:
                layout.append(("text", pos))
                pos += 1
        encoded = clip.encode_from_tokens_scheduled(tokens)
    if len(encoded) != 1:
        raise RuntimeError(f"scheduled encode returned {len(encoded)} sections")
    cond, extras = encoded[0][0], encoded[0][1]
    print(f"VL image encode: {probe} ({pos} rows)", flush=True)
    if cond.shape[1] != pos:
        raise RuntimeError(f"VL image encode has {cond.shape[1]} rows, expected {pos}")
    tags = extras.get("minimax_token_tags")
    if tags is None or int(tags.shape[0]) != pos:
        raise RuntimeError("minimax_token_tags missing or misaligned")
    del clip
    ab_models.free_gpu()

    cond, tags = cond.cpu(), tags.cpu()
    cache.parent.mkdir(parents=True, exist_ok=True)
    torch.save({"cond": cond, "tags": tags, "layout": layout}, cache)
    return cond, tags, layout


def resample_for_caption(tile_pixels):
    """AB27's caption input prep: area-resample a COPY of the crop to 384^2 px."""
    import math

    import comfy.utils

    samples = tile_pixels.float().movedim(-1, 1)
    scale_by = math.sqrt(384 * 384 / (samples.shape[3] * samples.shape[2]))
    width = round(samples.shape[3] * scale_by)
    height = round(samples.shape[2] * scale_by)
    resampled = comfy.utils.common_upscale(samples, width, height, "area", "disabled")
    return resampled.movedim(1, -1)[:, :, :, :3]


def _usable(text):
    """A caption must carry words — degenerate decodes (comma streams) are non-empty
    but conditioning-meaningless."""
    return any(ch.isalpha() for ch in text)


def generate_caption(clip, vl_input):
    """run_ab_krea2.generate_caption with the emptiness guards widened to _usable():
    greedy decode + the settled fallback chain."""
    tokens = clip.tokenize(CAPTION_INSTRUCTION, images=[vl_input], thinking=False)
    ids = clip.generate(tokens, do_sample=False, max_length=512, repetition_penalty=1.05)
    text = clip.decode(ids).strip()
    if not _usable(text):
        print(f"[caption] unusable answer (raw: {clip.decode(ids, skip_special_tokens=False)[:120]!r}); trying fallbacks", flush=True)
        ids = clip.generate(tokens, do_sample=True, max_length=512, temperature=0.7,
                            top_k=64, top_p=0.95, min_p=0.05, repetition_penalty=1.05, seed=42)
        text = clip.decode(ids).strip()
    if not _usable(text):
        retokens = clip.tokenize("Write one short sentence describing this image.",
                                 images=[vl_input], thinking=False)
        ids = clip.generate(retokens, do_sample=False, max_length=512, repetition_penalty=1.05)
        text = clip.decode(ids).strip()
    if not _usable(text):
        raise RuntimeError(f"caption generation: unusable after fallbacks (raw: {clip.decode(ids, skip_special_tokens=False)[:120]!r})")
    return text


def build_caption_arms(frame_up, up, force):
    """One CLIP session for everything the caption arms need: per-tile captions
    (JSON-cached so cap and vlcap share identical text), the cap arm's plain-text
    conds, and the vlcap arm's per-caption canvas encodes (image presentation with
    the caption as the prompt tail — grid rows precede the caption, so causality
    keeps them identical to the pure-vl encode; the caption rows ride behind)."""
    import hashlib

    rects = [r["crop"] for r in stress.tile_rects()]
    key = dict(FRAME_KEY, rects=rects, instruction=CAPTION_INSTRUCTION,
               captioner=CAPTIONER_CLIP_NAME)
    digest = hashlib.sha256(json.dumps(key, sort_keys=True, default=str).encode()).hexdigest()[:12]
    caption_cache = CACHE_DIR / f"h3frame_captions_{digest}.json"

    if caption_cache.is_file() and not force:
        captions = json.loads(caption_cache.read_text(encoding="utf-8"))["captions"]
        print(f"[caption] cache hit  {caption_cache.name}", flush=True)
    else:
        ab_models.free_gpu()
        captioner = ab_models.load_clip(CAPTIONER_CLIP_NAME, CAPTIONER_CLIP_TYPE)
        captions = []
        for rect in stress.tile_rects():
            x0, y0, x1, y1 = rect["crop"]
            with torch.inference_mode():
                captions.append(generate_caption(
                    captioner,
                    resample_for_caption(up[FRAME_INDEX:FRAME_INDEX + 1, y0:y1, x0:x1, :])))
        del captioner
        ab_models.free_gpu()
        caption_cache.parent.mkdir(parents=True, exist_ok=True)
        caption_cache.write_text(json.dumps(dict(key, captions=captions), indent=1),
                                 encoding="utf-8")
    for index, caption in enumerate(captions):
        print(f"[caption] tile {index}: {caption}", flush=True)

    ab_models.free_gpu()
    clip = ab_models.load_clip(poc.CLIP_NAME, poc.CLIP_TYPE)

    rows_per_block = (UP_H // 32) * (UP_W // 32)
    cap_conds, vlcap_packs = [], []
    with torch.inference_mode():
        for caption in captions:
            encoded = clip.encode_from_tokens_scheduled(clip.tokenize(caption))
            cap_conds.append([[encoded[0][0].cpu(), {
                k: (v.cpu() if isinstance(v, torch.Tensor) else v)
                for k, v in encoded[0][1].items()}]])

            tokens = clip.tokenize(caption, images=[frame_up])
            layout = []
            pos = 0
            for entry in tokens["qwen3vl_32b"][0]:
                if isinstance(entry[0], dict):
                    layout.append(("grid", pos))
                    pos += rows_per_block
                else:
                    layout.append(("text", pos))
                    pos += 1
            encoded = clip.encode_from_tokens_scheduled(tokens)
            cond, extras = encoded[0][0], encoded[0][1]
            if cond.shape[1] != pos:
                raise RuntimeError(f"vlcap encode has {cond.shape[1]} rows, expected {pos}")
            tags = extras.get("minimax_token_tags")
            if tags is None or int(tags.shape[0]) != pos:
                raise RuntimeError("vlcap minimax_token_tags missing or misaligned")
            vlcap_packs.append((cond.cpu(), tags.cpu(), layout))
    del clip
    ab_models.free_gpu()
    return captions, cap_conds, vlcap_packs


def refine_frame(model, vae, up, tile_positive_fn, denoise, noise_pack, audio_zeros):
    """One 2x2 tiled refine of the single frame. Returns the refined [T,H,W,3] fp16."""
    live = up.clone()
    for index, rect in enumerate(stress.tile_rects()):
        tile_positive = tile_positive_fn(index, rect)
        crop = stress.assemble_crop(up, live, rect)
        z = poc.encode_video(vae, crop)
        expected = (1, 24, LATENT_T,
                    (rect["crop"][3] - rect["crop"][1]) // 16,
                    (rect["crop"][2] - rect["crop"][0]) // 16)
        if tuple(z.shape) != expected:
            raise RuntimeError(f"tile latent {tuple(z.shape)} != expected {expected} — {FRAMES}-frame encode drifted"
                               )
        del crop
        refined = stress.refine_tile(
            model, tile_positive, z, audio_zeros,
            stress.anchor_mask(z, rect), denoise,
            stress.SlicedNoise(poc.REFINE_SEED, noise_pack, rect))
        del z
        tile_frames = poc.decode_video(vae, refined).to(torch.float16)
        del refined

        (px0, py0, px1, py1), alpha = stress.paste_alpha(rect)
        x0, y0 = rect["crop"][0], rect["crop"][1]
        region = tile_frames[:, py0 - y0:py1 - y0, px0 - x0:px1 - x0, :]
        blend = alpha.view(1, alpha.shape[0], alpha.shape[1], 1)
        live[:, py0:py1, px0:px1, :] = (
            region.float() * blend + live[:, py0:py1, px0:px1, :].float() * (1.0 - blend)
        ).to(torch.float16)
        del tile_frames, region
    return live


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--denoises", type=float, nargs="+", default=list(DEFAULT_DENOISES))
    parser.add_argument("--arms", nargs="+", choices=list(ARMS), default=["text", "vl"])
    parser.add_argument("--force", action="store_true")
    args = parser.parse_args()

    version = poc.ab_env.version(poc.ROOT)
    print(f"ComfyUI root: {poc.ROOT} ({poc.ROOT_NOTE}) version {version}", flush=True)

    vae = ab_models.load_vae(poc.VAE_NAME)
    up = upscaled_clip(vae)
    ab_models.save_png(OUTPUT_DIR / "H3F_upscaled.png", up[FRAME_INDEX:FRAME_INDEX + 1],
                       dict(FRAME_KEY, run_label="upscaled", conditioning="n/a",
                            comfyui_version=version))
    print(f"upscaled clip ready {tuple(up.shape)}", flush=True)

    text_positive = poc.get_positive(args.force)
    vl_pack = encode_image_vl(up[FRAME_INDEX:FRAME_INDEX + 1], args.force)
    captions, cap_conds, vlcap_packs = None, None, None
    if {"cap", "vlcap"} & set(args.arms):
        captions, cap_conds, vlcap_packs = build_caption_arms(
            up[FRAME_INDEX:FRAME_INDEX + 1], up, args.force)
    noise_pack = stress.canvas_noise(
        poc.REFINE_SEED, (1, 24, LATENT_T, UP_H // 16, UP_W // 16), (1, 32, 2, AUDIO_T))
    audio_zeros = torch.zeros([1, 32, 2, AUDIO_T])

    providers = {
        "text": lambda i, r: text_positive,
        "vl": lambda i, r: stress.vl_slice(*vl_pack, r),
        "cap": lambda i, r: cap_conds[i],
        "vlcap": lambda i, r: stress.vl_slice(*vlcap_packs[i], r),
    }
    conditioning_labels = {"text": "text-prompt", "vl": "vl-slice",
                           "cap": "tile-captions", "vlcap": "vl-slice+captions"}

    model = ab_models.load_unet(poc.UNET_NAME)
    for arm in args.arms:
        for denoise in args.denoises:
            steps = max(1, round(poc.STEPS * denoise))
            effective = round(steps / int(steps / denoise), 4)
            with ab_models.VramProbe() as probe:
                refined = refine_frame(model, vae, up, providers[arm], denoise,
                                       noise_pack, audio_zeros)
            label = f"H3F_{arm}_d{denoise * 100:02.0f}"
            settings = dict(FRAME_KEY, run_label=label,
                            conditioning=conditioning_labels[arm], denoise=denoise,
                            denoise_effective=effective, refine_seed=poc.REFINE_SEED,
                            comfyui_version=version)
            if arm in ("cap", "vlcap"):
                settings["captions"] = captions
            ab_models.save_png(
                OUTPUT_DIR / (label + ".png"), refined[FRAME_INDEX:FRAME_INDEX + 1],
                settings)
            print(f"{label}: {probe}  (effective denoise {effective})",
                  flush=True)
            del refined
    del model
    ab_models.free_gpu()
    print(f"done. sweep in {OUTPUT_DIR}", flush=True)
    print(json.dumps({"denoises": args.denoises, "frame": FRAME_INDEX}), flush=True)


if __name__ == "__main__":
    main()
